version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_NO_CACHE=--no-cache
    ports:
      - "3000:3000"
    working_dir: /app
    command: ["bash", "-lc", "bundle exec cucumber"]
